const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const MAX_NOTIFICATIONS = process.env.REACT_APP_MAX_NOTIFICATIONS;
const TIME_LOADING_ANIMATION = process.env.REACT_APP_TIME_LOADING_ANIMATION;

export { BACKEND_URL, MAX_NOTIFICATIONS, TIME_LOADING_ANIMATION };
